name: Backend Linters

on:
  pull_request:
    paths:
      - "backend/**"

env:
  GITHUB_WORKFLOW: github_actions

jobs:
  ruff:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install ruff
        working-directory: ${{env.working-directory}}
        run: |
          python -m pip install ruff
      - name: Run ruff format check
        working-directory: ${{env.working-directory}}
        run: ruff format --check .
      # NOTE: The following will be uncommented once the codebase is cleaned up
      # - name: ruff
      #   working-directory: ${{env.working-directory}}
      #   run: ruff check .
